### ISSUE TITLE
DNS Resolution Error

### ISSUE THREAD

**Issue by pmdevita** [pmdevita/GifReversingBot#23]
```
Traceback (most recent call last):
  File "/home/pmdevita/.local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/pmdevita/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pmdevita/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/pmdevita/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/pmdevita/.local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/pmdevita/.local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f458b4ba880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/pmdevita/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/pmdevita/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='v.redd.it', port=443): Max retries exceeded with url: /6j23cgfef4l61/DASH_480.mp4?source=fallback (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x
7f458b4ba880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 62, in <module>
    result = process_comment(reddit, reddit.comment(message.id), q)
  File "/home/pmdevita/bots/vredditshare/core/process.py", line 110, in process_comment
    if not new_original_gif.analyze():
  File "/home/pmdevita/bots/vredditshare/core/hosts/reddit.py", line 43, in analyze
    r = requests.get(url)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='v.redd.it', port=443): Max retries exceeded with url: /6j23cgfef4l61/DASH_480.mp4?source=fallback (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at
 0x7f458b4ba880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
Strange error happening on server. Uncommon and reason for happening is uncertain. Seems to happen sometimes on both vreddit and gfycat requests. Is this being caused by the server's DNS failing or something?

**Comment by pmdevita** [comment]
Seems that I'm getting rate limited, getting a list of the endpoints that do this would be the next big step.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 66, in <module>
    result = process_comment(reddit, reddit.comment(message.id), q)
  File "/home/pmdevita/bots/gifreversingbot/core/process.py", line 173, in process_comment
    result = options[0]['hosts'][0].upload(reversed_gif_file.file, reversed_gif_file.type,
  File "/home/pmdevita/bots/gifreversingbot/core/hosts/gfycat.py", line 331, in upload
    id = cls.API.upload(file, gif_type, nsfw=nsfw, audio=audio)
  File "/home/pmdevita/bots/gifreversingbot/core/hosts/gfycat.py", line 203, in upload
    r = requests.get(url, headers=headers)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pmdevita/.local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.gfycat.com', port=443): Max retries exceeded with url: /v1/gfycats/fetch/status/DistantImaginaryArcticwolf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f14a38a0f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
