### ISSUE TITLE
Imgur crash

### ISSUE THREAD

**Issue by pmdevita** [pmdevita/GifReversingBot#6]
Seems Imgur has been having load problems recently

```
uploading... Traceback (most recent call last):
  File "main.py", line 55, in <module>
    result = process_comment(reddit, reddit.comment(message.id), q)
  File "/home/pmdevita/bots/vredditshare/core/process.py", line 155, in process_comment
    original_gif_file.audio)
  File "/home/pmdevita/bots/vredditshare/core/hosts/imgur.py", line 349, in upload
    id = imgurupload(file, gif_type, nsfw=nsfw)
  File "/home/pmdevita/bots/vredditshare/core/hosts/imgur.py", line 160, in imgurupload
    print("received wait ticket:", upload['data']['ticket'])
UnboundLocalError: local variable 'upload' referenced before assignment
```

**Comment by pmdevita** [comment]
Confirming this hasn't been fixed still

**Comment by pmdevita** [comment]
```
uploading... wat
{'data': {'error': {'code': 1001,
                    'exception': {},
                    'message': '[PCceSFe]: Failed stripping metadata',
                    'type': 'Exception_UploadError'},
          'method': 'POST',
          'request': '/upload'},
 'status': 500,
 'success': False}
```
What Imgur returns during this crash

**Comment by pmdevita** [comment]
Imgur API has since been rewritten, this bug likely no longer exists. Closing.
